---
- hosts: localhost
  become: true
  become_user: root
  tasks:
    - name: Build my docker image
      docker_image:
        name: myimage
        build:
          path: .
          args:
            listen_port: 80
        source: build