---
- hosts: localhost
  become: true
  become_user: root
  tasks:
    - name: Run my new image
      docker_container:
        name: myimage
        state: started
        image: "myimage:latest"
        pull: true
        ports: